//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MojaLista")]
[System.Xml.Serialization.XmlRootAttribute("ListaStudentow", Namespace="MojaLista", IsNullable=false)]
public partial class ListaStudentowType {
    
    private StudentType[] studentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Student")]
    public StudentType[] Student {
        get {
            return this.studentField;
        }
        set {
            this.studentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MojaLista")]
public partial class StudentType {
    
    private AdresType adresField;
    
    private AdresTymczasowyType adresTymczasowyField;
    
    private ZajeciaType[] listaZajecField;
    
    private string imieField;
    
    private string nazwiskoField;
    
    private System.DateTime dataUrodzeniaField;
    
    private string adresEmailField;
    
    /// <remarks/>
    public AdresType Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    public AdresTymczasowyType AdresTymczasowy {
        get {
            return this.adresTymczasowyField;
        }
        set {
            this.adresTymczasowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Zajecia", IsNullable=false)]
    public ZajeciaType[] ListaZajec {
        get {
            return this.listaZajecField;
        }
        set {
            this.listaZajecField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime DataUrodzenia {
        get {
            return this.dataUrodzeniaField;
        }
        set {
            this.dataUrodzeniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AdresEmail {
        get {
            return this.adresEmailField;
        }
        set {
            this.adresEmailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MojaLista")]
public partial class AdresType {
    
    private string ulicaField;
    
    private int nrDomuField;
    
    private int mieszkanieField;
    
    private bool mieszkanieFieldSpecified;
    
    private string miastoField;
    
    private string kodPocztowyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NrDomu {
        get {
            return this.nrDomuField;
        }
        set {
            this.nrDomuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Mieszkanie {
        get {
            return this.mieszkanieField;
        }
        set {
            this.mieszkanieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MieszkanieSpecified {
        get {
            return this.mieszkanieFieldSpecified;
        }
        set {
            this.mieszkanieFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Miasto {
        get {
            return this.miastoField;
        }
        set {
            this.miastoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KodPocztowy {
        get {
            return this.kodPocztowyField;
        }
        set {
            this.kodPocztowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MojaLista")]
public partial class ZajeciaType {
    
    private string nazwaField;
    
    private int ocenaZCwiczenField;
    
    private bool ocenaZCwiczenFieldSpecified;
    
    private int ocenaZWykladuField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int OcenaZCwiczen {
        get {
            return this.ocenaZCwiczenField;
        }
        set {
            this.ocenaZCwiczenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OcenaZCwiczenSpecified {
        get {
            return this.ocenaZCwiczenFieldSpecified;
        }
        set {
            this.ocenaZCwiczenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int OcenaZWykladu {
        get {
            return this.ocenaZWykladuField;
        }
        set {
            this.ocenaZWykladuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="MojaLista")]
public partial class AdresTymczasowyType {
    
    private string ulicaField;
    
    private int nrDomuField;
    
    private int mieszkanieField;
    
    private bool mieszkanieFieldSpecified;
    
    private string miastoField;
    
    private string kodPocztowyField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NrDomu {
        get {
            return this.nrDomuField;
        }
        set {
            this.nrDomuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Mieszkanie {
        get {
            return this.mieszkanieField;
        }
        set {
            this.mieszkanieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MieszkanieSpecified {
        get {
            return this.mieszkanieFieldSpecified;
        }
        set {
            this.mieszkanieFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Miasto {
        get {
            return this.miastoField;
        }
        set {
            this.miastoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KodPocztowy {
        get {
            return this.kodPocztowyField;
        }
        set {
            this.kodPocztowyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
