<?xml version="1.0" encoding="utf-8"?><Database Name="aspdotnet" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GLADOS\SQLEXPRESS;Initial Catalog=aspdotnet;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspdotnetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PASSWORD" Member="PASSWORD">
    <Type Name="PASSWORD">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Member="password1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="USER_PASSWORD" Member="USER" ThisKey="userID" OtherKey="id" Type="USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.USERSROLES" Member="USERSROLES">
    <Type Name="USERSROLES">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="USER_USERSROLES" Member="USER" ThisKey="userID" OtherKey="id" Type="USER" IsForeignKey="true" />
      <Association Name="ROLES_USERSROLES" Member="ROLES" ThisKey="roleID" OtherKey="id" Type="ROLES" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[USER]" Member="USER">
    <Type Name="USER">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="USER_PASSWORD" Member="PASSWORD" ThisKey="id" OtherKey="userID" Type="PASSWORD" />
      <Association Name="USER_USERSROLES" Member="USERSROLES" ThisKey="id" OtherKey="userID" Type="USERSROLES" />
    </Type>
  </Table>
  <Table Name="dbo.ROLES" Member="ROLES">
    <Type Name="ROLES">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roleName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ROLES_USERSROLES" Member="USERSROLES" ThisKey="id" OtherKey="roleID" Type="USERSROLES" />
    </Type>
  </Table>
</Database>