<?xml version="1.0" encoding="utf-8"?><Database Name="aspdotnet" Class="PERSONDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=GLADOS\SQLEXPRESS;Initial Catalog=aspdotnet;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspdotnetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="lista7.PERSON" Member="PERSON">
    <Type Name="PERSON">
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
    </Type>
  </Table>
</Database>