[package]
name = "zad2"
version = "0.1.0"
authors = ["doubleduck98 <szymon.zienkiewicz98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
